### ISSUE TITLE
Images continuously loading

### ISSUE THREAD

**Issue by benjamin072** [kalibrado/jf-avatars#16]
Hi,

First of all, thank you for the work you've done - the script looks clean with Jellyfin.

The issue I'm having is the avatar images continuously loading. I haven't been able to load images to select.

I've injected the following script into /usr/share/jellyfin/web/index.html:
`<script src="https://github.com/kalibrado/jf-avatars/releases/download/2.2.0/main.js"></script>`

Screenshots of what I'm seeing:

_Desktop:_

![Image](https://github.com/user-attachments/assets/8675613b-5f01-4a46-a615-ffc1db909f4a)

_Android:_

![Image](https://github.com/user-attachments/assets/801411a6-c9ab-4ef9-98a2-e9722f5eb352)

**Comment by benjamin072** [comment]
My bad - I didn't notice an existing issue. Closing as duplicate

**Comment by benjamin072** [comment]
Reopening issue as the [generate_constants.py](https://github.com/kalibrado/jf-avatars/blob/main/src/scripts/generate_constants.py) no longer exists.

**Comment by kalibrado** [comment]
Hello  @benjamin072,
Thanks again for your feedback and for reopening the thread to highlight it! 🙏

You were right: there was indeed a small bug.
In the loadSrcImages function, I was unnecessarily checking response.ok after calling tryLoadJson, even though tryLoadJson already handles retrieval errors internally.
As a result, when avatar images failed to load, they remained stuck in an infinite loading state instead of properly returning to their initial state.

I just fixed the issue! The fix will be available in the next release (v2.2.1).
Thank you very much for reporting it; your report has helped improve the project!

If you have any other issues or suggestions, please feel free to contact me 🚀

**Comment by benjamin072** [comment]
Hi @kalibrado, thank you for the quick reply and addressing the issue. However, it still seems to be happening. Inspecting network whilst loading the avatars, I'm able to see that a few are being pulled, but it is stuck on the loading

![Image](https://github.com/user-attachments/assets/75e5d869-8b63-4010-9e04-b18ebbcc03af)

**Comment by benjamin072** [comment]
I'm not experienced with JS, so I'm not sure if this helps, but looking at the console I see the following:

![Image](https://github.com/user-attachments/assets/c11d280c-61f9-4fe5-92c4-15b64eaae466)

fyi - this is in a JF docker container; I don't believe this should be an issue but might be helpful in case you try to reproduce.

**Comment by kalibrado** [comment]
Hello @benjamin072 ,

Thank you for the screenshots and additional information. I believe I've identified the issue!

The problem doesn't seem to be with the code itself, but rather with how the script is injected into the page. I notice that you used:

```html
<script src="https://github.com/kalibrado/jf-avatars/releases/download/2.2.1/main.js"></script>
```

The `defer` attribute is missing from this script tag. Without this attribute, the script executes immediately during page loading, before all DOM elements are available, which can cause exactly the behavior you're observing.

Could you try modifying the injection like this:

```html
<script defer src="https://github.com/kalibrado/jf-avatars/releases/download/2.2.1/main.js"></script>
```

The `defer` attribute ensures that the script only runs after the entire HTML document has been loaded and parsed, which should resolve these 404 errors and the infinite loading issue.

Let me know if this fixes your problem!

**Comment by benjamin072** [comment]
Hi @kalibrado,

I've updated my injection to <script defer src="https://github.com/kalibrado/jf-avatars/releases/download/2.2.1/main.js"></script> but it's still not showing the avatars/forever loading.

I'm also still seeing the following in the browser console: 
```
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'style')
    at main.js:2:46564
```

Is there any debugging you would recommend for me to do to help pinpoint the problem?

**Comment by kalibrado** [comment]
Hey 👋  
Just a quick suggestion: have you tried importing the script **without `defer`**, placing it **right before the `</body>` tag**? It might help with the loading.

Also, you can add this to your CSS (in the Jellyfin dashboard, under the Custom CSS section) to get a bit more console output for debugging:

```css
:root {
  --jf-avatars-debug: "true";
}
```

**Comment by benjamin072** [comment]
Hi @kalibrado,

Thanks for the quick response 😄 without the defer is how I previously had it, and I've been placing it before </body> tag.

The debugging has done the trick, I'm now seeing: 

`Failed to load resource: the server responded with a status of 404 (Not Found)    web/jf-avatars/src/lang/en.json:1`

Is there any pre-requisite to install these files that I've missed?

**Comment by kalibrado** [comment]
We're making great progress with the debugging, that's awesome! 😄  

The error related to loading the language file probably comes from my function.  
It first tries to load the language locally by checking for the presence of a folder.  
If the folder isn't found, it falls back to loading from the GitHub source.  

I'll investigate on my side and work on making this part of the code more robust!

**Comment by benjamin072** [comment]
Hi @kalibrado,

Apologies, I've been busy and haven't tried anything else until today. I tried cloning the src folder from the recent release and placing it under /usr/share/jellyfin/web/jf-avatars/src to see if it could detect the language file locally. But that created the same error as last time:

`Failed to load resource: the server responded with a status of 404 (Not Found)    web/jf-avatars/src/lang/en.json:1`

Where should I place the src folder locally to see if it works without speaking to GitHub?

**Comment by kalibrado** [comment]
Hi @benjamin072

To make it work locally, you need to ensure that the path in your <script> tag in your index file matches the actual location of the index.js file on your server.

For example, if your index.js is located at /jf-avatars/src/js/index.js, your HTML should have:

```html
<script type="module" src="/jf-avatars/src/js/index.js"></script>
```
If the path in the script tag does not correspond to the real location of the file, you will get a 404 error.
So, make sure that the path in your index file matches exactly where the file is on your server.

Let me know if you need more help!

**Comment by benjamin072** [comment]
Hi @kalibrado, 

Thank you for the detailed instructions. I've been able to locally install the files, however the images are still not coming through.. The file path is identical to the instructions, and I can confirm the language files are in the correct location (ls command shows expected files, and no longer seeing the error previously reported).

What I'm seeing now is the following:

_After clicking on the 'More Avatars' button on the profile page_
![Image](https://github.com/user-attachments/assets/81a2796d-092d-4e26-b1de-f783e96ef8c0)


_After changing the option under 'Filter by category'_
![Image](https://github.com/user-attachments/assets/352f143b-9dff-4d06-8fc4-ca243d46468a)

**Comment by benjamin072** [comment]
Apologies @kalibrado for all of the comments, I have figured out the cause and have raised #18

**Comment by kalibrado** [comment]
Hi @benjamin072,

Don't worry at all! 😄 Thank you so much for digging and opening #18 — you're awesome! 🚀🙌
